# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headImg', models.CharField(max_length=999)),
                ('username', models.CharField(max_length=30)),
                ('kap', models.CharField(max_length=30)),
                ('C_lass', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('zan', models.IntegerField()),
                ('cai', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headImg', models.ImageField(upload_to='./upload/')),
                ('username', models.CharField(max_length=30)),
                ('kap', models.CharField(max_length=30)),
                ('C_lass', models.CharField(max_length=30)),
            ],
        ),
    ]
